export const projects = [
  { title: "Jipe Ehelor", kind: "Brand identity", category: "identity", id: "upper_logo_014412_qkb9ke", description: "A bold, high-energy wordmark designed to make the name impossible to miss.", alt: "Blue and white Jipe Ehelor logo design", tone: "blue" },
  { title: "Path — Focus Forward", kind: "Brand campaign", category: "campaign", id: "path_branding_040916_vz3qqv", description: "A fresh visual direction built around clarity, optimism and forward motion.", alt: "Green Path brand campaign artwork", tone: "green" },
  { title: "WCC", kind: "Visual identity", category: "identity", id: "WC_040259_gkutap", description: "A clean, confident mark for a contemporary watch and style brand.", alt: "WCC watch and style brand mark", tone: "light" },
  { title: "Great Men", kind: "Campaign artwork", category: "campaign", id: "great_men.png1_033746_y5xmdo", description: "A high-impact event creative with a strong headline and a clear focal point.", alt: "Great Men campaign artwork", tone: "light" },
  { title: "Campus Trade", kind: "Digital creative", category: "digital", id: "campus_trade_070205_wwae6h", description: "Social-first artwork built to feel energetic, useful and easy to recognise.", alt: "Campus Trade social media design", tone: "blue" },
  { title: "Path — New Month", kind: "Campaign artwork", category: "campaign", id: "path_new_month.pngjk_125806_zmx5au", description: "A recurring campaign visual system designed to keep every new message on-brand.", alt: "Path new month campaign artwork", tone: "green" },
  { title: "October", kind: "Event creative", category: "campaign", id: "OCTO_043104_mdxbmy", description: "A purposeful event graphic with a sharp hierarchy and memorable colour.", alt: "October event campaign graphic", tone: "orange" },
  { title: "Miracle Service", kind: "Event creative", category: "campaign", id: "mirracle_service_043029_hnwpla", description: "A faith-centred event visual composed to feel uplifting and immediate.", alt: "Miracle Service event flyer", tone: "orange" },
  { title: "Manifest — May", kind: "Event creative", category: "campaign", id: "manifest_may_053436_1_v4ltzg", description: "A vibrant event announcement shaped for fast, clear reading on mobile.", alt: "Manifest May event graphic", tone: "orange" },
  { title: "Just Worship", kind: "Event creative", category: "campaign", id: "JUST_WSHP_111814_zp1hcv", description: "Atmospheric worship-night artwork with a focused message and expressive tone.", alt: "Just Worship event design", tone: "dark" },
  { title: "Hangout", kind: "Digital creative", category: "digital", id: "HANGOUT_115955_inceyy", description: "A social event visual designed to feel welcoming, lively and shareable.", alt: "Hangout event social graphic", tone: "light" },
  { title: "Path — Brand world", kind: "Brand identity", category: "identity", id: "path_branding_070856_fwdwod", description: "A companion piece from the Path identity system, extending the brand into digital use.", alt: "Path green brand identity artwork", tone: "green" },
];
